# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d138cb57d9f51cd2ab5476ca80a2ae546f1098a674577b822520c528489f8a2cca2c2ee02ffde9b52d24833e17a674ba53629bafe1e2828d9dc876c22ff0a6

test:
  secret_key_base: 36646ebe20fd0b86bb4a96271efd1f52400cf683105e06249c4a99110aced243c0a49bf50f2f92e61ab74d1770960a11f1f649d0e2d173f7c2cbd13d21942a30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
